"""empty message

Revision ID: 4653cf95a9a3
Revises: ee5f9668dc09
Create Date: 2019-10-06 01:01:43.768450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4653cf95a9a3'
down_revision = 'ee5f9668dc09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_l_board_record_score'), 'l_board_record', ['score'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_l_board_record_score'), table_name='l_board_record')
    # ### end Alembic commands ###
