"""empty message

Revision ID: ee5f9668dc09
Revises: 7fe036230ea6
Create Date: 2019-10-05 17:15:43.155708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee5f9668dc09'
down_revision = '7fe036230ea6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_l_board_record_name', table_name='l_board_record')
    op.create_index(op.f('ix_l_board_record_name'), 'l_board_record', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_l_board_record_name'), table_name='l_board_record')
    op.create_index('ix_l_board_record_name', 'l_board_record', ['name'], unique=1)
    # ### end Alembic commands ###
