"""empty message

Revision ID: f701dcfab562
Revises: 4653cf95a9a3
Create Date: 2019-12-17 23:46:55.095226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f701dcfab562'
down_revision = '4653cf95a9a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.drop_index('ix_l_board_record_name', table_name='l_board_record')
    op.drop_index('ix_l_board_record_score', table_name='l_board_record')
    op.drop_table('l_board_record')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('l_board_record',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('score', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_l_board_record_score', 'l_board_record', ['score'], unique=False)
    op.create_index('ix_l_board_record_name', 'l_board_record', ['name'], unique=False)
    op.drop_table('user')
    # ### end Alembic commands ###
